name    'dexterp/galera'
version '0.2.0'
source 'git://github.com/dexterp/dexterp-galera.git'
author 'Dexter Plameras'
license 'Apache License, Version 2.0'
summary 'Galera Cluster'
description 'Galera Cluster'
project_page 'http://github.com/dexterp/dexterp-galera'
dependency 'puppetlabs/mysql', '>= 2.1.0'
